/**
 * Global HTMLElementTagNameMap declarations for DUI components.
 * Provides type-safe `document.querySelector("dui-button")` etc.
 *
 * These declarations are automatically available when consuming
 * @deepfuture/dui-components via TypeScript.
 */

import type { DuiAccordionPrimitive } from "./accordion/accordion.ts";
import type { DuiAccordionItemPrimitive } from "./accordion/accordion-item.ts";
import type { DuiAlertDialogPrimitive } from "./alert-dialog/alert-dialog.ts";
import type { DuiAlertDialogTriggerPrimitive } from "./alert-dialog/alert-dialog-trigger.ts";
import type { DuiAlertDialogPopupPrimitive } from "./alert-dialog/alert-dialog-popup.ts";
import type { DuiAlertDialogClosePrimitive } from "./alert-dialog/alert-dialog-close.ts";
import type { DuiAvatarPrimitive } from "./avatar/avatar.ts";
import type { DuiBadgePrimitive } from "./badge/badge.ts";
import type { DuiBreadcrumbPrimitive } from "./breadcrumb/breadcrumb.ts";
import type { DuiBreadcrumbItemPrimitive } from "./breadcrumb/breadcrumb-item.ts";
import type { DuiBreadcrumbLinkPrimitive } from "./breadcrumb/breadcrumb-link.ts";
import type { DuiBreadcrumbPagePrimitive } from "./breadcrumb/breadcrumb-page.ts";
import type { DuiBreadcrumbSeparatorPrimitive } from "./breadcrumb/breadcrumb-separator.ts";
import type { DuiBreadcrumbEllipsisPrimitive } from "./breadcrumb/breadcrumb-ellipsis.ts";
import type { DuiButtonPrimitive } from "./button/button.ts";
import type { DuiCalendarPrimitive } from "./calendar/calendar.ts";
import type { DuiCheckboxPrimitive } from "./checkbox/checkbox.ts";
import type { DuiCheckboxGroupPrimitive } from "./checkbox/checkbox-group.ts";
import type { DuiCollapsiblePrimitive } from "./collapsible/collapsible.ts";
import type { DuiComboboxPrimitive } from "./combobox/combobox.ts";
import type { DuiCommandPrimitive } from "./command/command.ts";
import type { DuiCommandInputPrimitive } from "./command/command-input.ts";
import type { DuiCommandListPrimitive } from "./command/command-list.ts";
import type { DuiCommandGroupPrimitive } from "./command/command-group.ts";
import type { DuiCommandItemPrimitive } from "./command/command-item.ts";
import type { DuiCommandEmptyPrimitive } from "./command/command-empty.ts";
import type { DuiCommandSeparatorPrimitive } from "./command/command-separator.ts";
import type { DuiCommandShortcutPrimitive } from "./command/command-shortcut.ts";
import type { DuiDataTablePrimitive } from "./data-table/data-table.ts";
import type { DuiDialogPrimitive } from "./dialog/dialog.ts";
import type { DuiDialogTriggerPrimitive } from "./dialog/dialog-trigger.ts";
import type { DuiDialogPopupPrimitive } from "./dialog/dialog-popup.ts";
import type { DuiDialogClosePrimitive } from "./dialog/dialog-close.ts";
import type { DuiDropzonePrimitive } from "./dropzone/dropzone.ts";
import type { DuiIconPrimitive } from "./icon/icon.ts";
import type { DuiInputPrimitive } from "./input/input.ts";
import type { DuiMenuPrimitive } from "./menu/menu.ts";
import type { DuiMenuItemPrimitive } from "./menu/menu-item.ts";
import type { DuiMenubarPrimitive } from "./menubar/menubar.ts";
import type { DuiNumberFieldPrimitive } from "./number-field/number-field.ts";
import type { DuiPopoverPrimitive } from "./popover/popover.ts";
import type { DuiPopoverTriggerPrimitive } from "./popover/popover-trigger.ts";
import type { DuiPopoverPopupPrimitive } from "./popover/popover-popup.ts";
import type { DuiPopoverClosePrimitive } from "./popover/popover-close.ts";
import type { DuiPortalPrimitive } from "./portal/portal.ts";
import type { DuiPreviewCardPrimitive } from "./preview-card/preview-card.ts";
import type { DuiPreviewCardTriggerPrimitive } from "./preview-card/preview-card-trigger.ts";
import type { DuiPreviewCardPopupPrimitive } from "./preview-card/preview-card-popup.ts";
import type { DuiProgressPrimitive } from "./progress/progress.ts";
import type { DuiRadioPrimitive } from "./radio/radio.ts";
import type { DuiRadioGroupPrimitive } from "./radio/radio-group.ts";
import type { DuiScrollAreaPrimitive } from "./scroll-area/scroll-area.ts";
import type { DuiSelectPrimitive } from "./select/select.ts";
import type { DuiSeparatorPrimitive } from "./separator/separator.ts";
import type { DuiSidebarProviderPrimitive } from "./sidebar/sidebar-provider.ts";
import type { DuiSidebarPrimitive } from "./sidebar/sidebar.ts";
import type { DuiSidebarTriggerPrimitive } from "./sidebar/sidebar-trigger.ts";
import type { DuiSidebarContentPrimitive } from "./sidebar/sidebar-content.ts";
import type { DuiSidebarHeaderPrimitive } from "./sidebar/sidebar-header.ts";
import type { DuiSidebarFooterPrimitive } from "./sidebar/sidebar-footer.ts";
import type { DuiSidebarGroupPrimitive } from "./sidebar/sidebar-group.ts";
import type { DuiSidebarGroupLabelPrimitive } from "./sidebar/sidebar-group-label.ts";
import type { DuiSidebarMenuPrimitive } from "./sidebar/sidebar-menu.ts";
import type { DuiSidebarMenuItemPrimitive } from "./sidebar/sidebar-menu-item.ts";
import type { DuiSidebarMenuButtonPrimitive } from "./sidebar/sidebar-menu-button.ts";
import type { DuiSidebarSeparatorPrimitive } from "./sidebar/sidebar-separator.ts";
import type { DuiSidebarInsetPrimitive } from "./sidebar/sidebar-inset.ts";
import type { DuiSliderPrimitive } from "./slider/slider.ts";
import type { DuiSpinnerPrimitive } from "./spinner/spinner.ts";
import type { DuiSwitchPrimitive } from "./switch/switch.ts";
import type { DuiTabsPrimitive } from "./tabs/tabs.ts";
import type { DuiTabsListPrimitive } from "./tabs/tabs-list.ts";
import type { DuiTabPrimitive } from "./tabs/tab.ts";
import type { DuiTabsPanelPrimitive } from "./tabs/tabs-panel.ts";
import type { DuiTabsIndicatorPrimitive } from "./tabs/tabs-indicator.ts";
import type { DuiTextareaPrimitive } from "./textarea/textarea.ts";
import type { DuiTogglePrimitive } from "./toggle/toggle.ts";
import type { DuiToggleGroupPrimitive } from "./toggle/toggle-group.ts";
import type { DuiToolbarPrimitive } from "./toolbar/toolbar.ts";
import type { DuiTooltipPrimitive } from "./tooltip/tooltip.ts";
import type { DuiTooltipTriggerPrimitive } from "./tooltip/tooltip-trigger.ts";
import type { DuiTooltipPopupPrimitive } from "./tooltip/tooltip-popup.ts";
import type { DuiTruncPrimitive } from "./trunc/trunc.ts";

declare global {
  interface HTMLElementTagNameMap {
    "dui-accordion": DuiAccordionPrimitive;
    "dui-accordion-item": DuiAccordionItemPrimitive;
    "dui-alert-dialog": DuiAlertDialogPrimitive;
    "dui-alert-dialog-trigger": DuiAlertDialogTriggerPrimitive;
    "dui-alert-dialog-popup": DuiAlertDialogPopupPrimitive;
    "dui-alert-dialog-close": DuiAlertDialogClosePrimitive;
    "dui-avatar": DuiAvatarPrimitive;
    "dui-badge": DuiBadgePrimitive;
    "dui-breadcrumb": DuiBreadcrumbPrimitive;
    "dui-breadcrumb-item": DuiBreadcrumbItemPrimitive;
    "dui-breadcrumb-link": DuiBreadcrumbLinkPrimitive;
    "dui-breadcrumb-page": DuiBreadcrumbPagePrimitive;
    "dui-breadcrumb-separator": DuiBreadcrumbSeparatorPrimitive;
    "dui-breadcrumb-ellipsis": DuiBreadcrumbEllipsisPrimitive;
    "dui-button": DuiButtonPrimitive;
    "dui-calendar": DuiCalendarPrimitive;
    "dui-checkbox": DuiCheckboxPrimitive;
    "dui-checkbox-group": DuiCheckboxGroupPrimitive;
    "dui-collapsible": DuiCollapsiblePrimitive;
    "dui-combobox": DuiComboboxPrimitive;
    "dui-command": DuiCommandPrimitive;
    "dui-command-input": DuiCommandInputPrimitive;
    "dui-command-list": DuiCommandListPrimitive;
    "dui-command-group": DuiCommandGroupPrimitive;
    "dui-command-item": DuiCommandItemPrimitive;
    "dui-command-empty": DuiCommandEmptyPrimitive;
    "dui-command-separator": DuiCommandSeparatorPrimitive;
    "dui-command-shortcut": DuiCommandShortcutPrimitive;
    "dui-data-table": DuiDataTablePrimitive;
    "dui-dialog": DuiDialogPrimitive;
    "dui-dialog-trigger": DuiDialogTriggerPrimitive;
    "dui-dialog-popup": DuiDialogPopupPrimitive;
    "dui-dialog-close": DuiDialogClosePrimitive;
    "dui-dropzone": DuiDropzonePrimitive;
    "dui-icon": DuiIconPrimitive;
    "dui-input": DuiInputPrimitive;
    "dui-menu": DuiMenuPrimitive;
    "dui-menu-item": DuiMenuItemPrimitive;
    "dui-menubar": DuiMenubarPrimitive;
    "dui-number-field": DuiNumberFieldPrimitive;
    "dui-popover": DuiPopoverPrimitive;
    "dui-popover-trigger": DuiPopoverTriggerPrimitive;
    "dui-popover-popup": DuiPopoverPopupPrimitive;
    "dui-popover-close": DuiPopoverClosePrimitive;
    "dui-portal": DuiPortalPrimitive;
    "dui-preview-card": DuiPreviewCardPrimitive;
    "dui-preview-card-trigger": DuiPreviewCardTriggerPrimitive;
    "dui-preview-card-popup": DuiPreviewCardPopupPrimitive;
    "dui-progress": DuiProgressPrimitive;
    "dui-radio": DuiRadioPrimitive;
    "dui-radio-group": DuiRadioGroupPrimitive;
    "dui-scroll-area": DuiScrollAreaPrimitive;
    "dui-select": DuiSelectPrimitive;
    "dui-separator": DuiSeparatorPrimitive;
    "dui-sidebar-provider": DuiSidebarProviderPrimitive;
    "dui-sidebar": DuiSidebarPrimitive;
    "dui-sidebar-trigger": DuiSidebarTriggerPrimitive;
    "dui-sidebar-content": DuiSidebarContentPrimitive;
    "dui-sidebar-header": DuiSidebarHeaderPrimitive;
    "dui-sidebar-footer": DuiSidebarFooterPrimitive;
    "dui-sidebar-group": DuiSidebarGroupPrimitive;
    "dui-sidebar-group-label": DuiSidebarGroupLabelPrimitive;
    "dui-sidebar-menu": DuiSidebarMenuPrimitive;
    "dui-sidebar-menu-item": DuiSidebarMenuItemPrimitive;
    "dui-sidebar-menu-button": DuiSidebarMenuButtonPrimitive;
    "dui-sidebar-separator": DuiSidebarSeparatorPrimitive;
    "dui-sidebar-inset": DuiSidebarInsetPrimitive;
    "dui-slider": DuiSliderPrimitive;
    "dui-spinner": DuiSpinnerPrimitive;
    "dui-switch": DuiSwitchPrimitive;
    "dui-tabs": DuiTabsPrimitive;
    "dui-tabs-list": DuiTabsListPrimitive;
    "dui-tab": DuiTabPrimitive;
    "dui-tabs-panel": DuiTabsPanelPrimitive;
    "dui-tabs-indicator": DuiTabsIndicatorPrimitive;
    "dui-textarea": DuiTextareaPrimitive;
    "dui-toggle": DuiTogglePrimitive;
    "dui-toggle-group": DuiToggleGroupPrimitive;
    "dui-toolbar": DuiToolbarPrimitive;
    "dui-tooltip": DuiTooltipPrimitive;
    "dui-tooltip-trigger": DuiTooltipTriggerPrimitive;
    "dui-tooltip-popup": DuiTooltipPopupPrimitive;
    "dui-trunc": DuiTruncPrimitive;
  }
}
